/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoManagerRouteImport } from './routes/demo-manager'
import { Route as DemoOpsRouteImport } from './routes/demo-ops'
import { Route as DemoWorkspaceRouteImport } from './routes/demo-workspace'
import { Route as ProductDemoManagerRouteImport } from './routes/product-demo-manager'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoManagerRoute = DemoManagerRouteImport.update({
  id: '/demo-manager',
  path: '/demo-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOpsRoute = DemoOpsRouteImport.update({
  id: '/demo-ops',
  path: '/demo-ops',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoWorkspaceRoute = DemoWorkspaceRouteImport.update({
  id: '/demo-workspace',
  path: '/demo-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductDemoManagerRoute = ProductDemoManagerRouteImport.update({
  id: '/product-demo-manager',
  path: '/product-demo-manager',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo-manager': typeof DemoManagerRoute
  '/demo-ops': typeof DemoOpsRoute
  '/demo-workspace': typeof DemoWorkspaceRoute
  '/product-demo-manager': typeof ProductDemoManagerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo-manager': typeof DemoManagerRoute
  '/demo-ops': typeof DemoOpsRoute
  '/demo-workspace': typeof DemoWorkspaceRoute
  '/product-demo-manager': typeof ProductDemoManagerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo-manager': typeof DemoManagerRoute
  '/demo-ops': typeof DemoOpsRoute
  '/demo-workspace': typeof DemoWorkspaceRoute
  '/product-demo-manager': typeof ProductDemoManagerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo-manager'
    | '/demo-ops'
    | '/demo-workspace'
    | '/product-demo-manager'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo-manager'
    | '/demo-ops'
    | '/demo-workspace'
    | '/product-demo-manager'
  id:
    | '__root__'
    | '/'
    | '/demo-manager'
    | '/demo-ops'
    | '/demo-workspace'
    | '/product-demo-manager'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoManagerRoute: typeof DemoManagerRoute
  DemoOpsRoute: typeof DemoOpsRoute
  DemoWorkspaceRoute: typeof DemoWorkspaceRoute
  ProductDemoManagerRoute: typeof ProductDemoManagerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-manager': {
      id: '/demo-manager'
      path: '/demo-manager'
      fullPath: '/demo-manager'
      preLoaderRoute: typeof DemoManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-ops': {
      id: '/demo-ops'
      path: '/demo-ops'
      fullPath: '/demo-ops'
      preLoaderRoute: typeof DemoOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-workspace': {
      id: '/demo-workspace'
      path: '/demo-workspace'
      fullPath: '/demo-workspace'
      preLoaderRoute: typeof DemoWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-demo-manager': {
      id: '/product-demo-manager'
      path: '/product-demo-manager'
      fullPath: '/product-demo-manager'
      preLoaderRoute: typeof ProductDemoManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoManagerRoute: DemoManagerRoute,
  DemoOpsRoute: DemoOpsRoute,
  DemoWorkspaceRoute: DemoWorkspaceRoute,
  ProductDemoManagerRoute: ProductDemoManagerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
